config/routes.rb
AAAWebsite::Application.routes.draw do
  resources :events

  match "/index" => "aaa_core#index", via: :get
  match "/shop" => "aaa_core#shop", via: :get
  match "/discussion" => "aaa_core#discussion", via: :get
  

  root 'aaa_core#index'	

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/aaa_core_controller.rb
class AaaCoreController < ApplicationController

  def index
	@title = "Home"
  end

  def shop
	@title = "Shop"
  end

  def discussion
	@title = "Discussion"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :date, :description)
    end
end

app/helpers/aaa_core_helper.rb
module AaaCoreHelper
end

app/helpers/application_helper.rb
#c:\Rails-Websites\AAA_Website\app\helpers\application_helper.rb
#
module ApplicationHelper

#Return a title on a per-page basis

def title
	base_title = "Ashtead Allotments Association"
	if @title.nil?
		base_title
	else
		"#{base_title} | #{@title}"
	 end
	end
	
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/aaa_core/discussion.html.erb
<h1>AaaCore#discussion</h1>
<p>Find me in app/views/aaa_core/discussion.html.erb</p>

app/views/aaa_core/events.html.erb
<h1>AaaCore#events</h1>
<p>Find me in app/views/aaa_core/events.html.erb</p>

app/views/aaa_core/index.html.erb
<h1>AaaCore#index</h1>
<p>Find me in app/views/aaa_core/index.html.erb</p>

app/views/aaa_core/shop.html.erb
<h1>AaaCore#shop</h1>
<p>Find me in app/views/aaa_core/shop.html.erb</p>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.date %></td>
        <td><%= event.description %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_footer.html.erb
<!--views\layouts\_footers.html.erb -->
<!-- -->

<footer>
<%= Time.now.year %> Ashtead Allotment's Associations
</footer>

app/views/layouts/_header.html.erb
<!-- Ruby Partials like... _header.html.erb notice the underscore __ -->
<!-- C:\Rails-Websites\AAA_Website\app\views\layouts\_header.html.erb -->
<!--  -->

<header>
<h1>Ashtead Allotments Association</h1>
<h2>Healthy Eating and Exercise preserve Life's Balance</h2>
</header>

app/views/layouts/_navigation.html.erb
<nav>

<ul>
	
	<li><%=link_to "Home", root_path %></li>	
	<li><%=link_to "events", events_path %></li>
	<li><%=link_to "Discussion", discussion_path %></li>
	<li><%=link_to "Shop", shop_path %></li>
	
</ul>

</nav>

app/views/layouts/application.html.erb
<!-- -->
<!--c:\Rails-Websites\AAA_Website\app\views\layouts\ application.html.erb -->
<!-- -->

<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= render 'layouts/navigation' %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>